import {useEffect,useState,type FormEvent} from 'react';
import {Search,Plus,Upload,ChevronLeft,ChevronRight,ArrowUpRight,FileSpreadsheet,CheckCircle2,History} from 'lucide-react';
import {type Api,type Client,cnpj} from './api';
import {Badge,Empty,ErrorBox,Field,Loading,Modal,SaveBar} from './ui';

const fields=['nome','cnpj','endereco','numero','complemento','bairro','cidade','estado','cep','telefone','email','contrato_status','numero_contrato'] as const;
export default function Clients({api,admin,changed,onHistory}:{api:Api;admin:boolean;changed:(s:string)=>void;onHistory:(client:Client)=>void}){
 const [items,setItems]=useState<Client[]>([]);const [total,setTotal]=useState(0);const [q,setQ]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [edit,setEdit]=useState<Client|null|undefined>(undefined);const [importing,setImporting]=useState(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);const timer=setTimeout(()=>{api<{items:Client[];total:number}>(`/clientes?q=${encodeURIComponent(q)}&limit=20&offset=${page*20}${status?'&ativo='+status:''}`,{signal:ctrl.signal}).then(data=>{setItems(data.items);setTotal(data.total);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false);});},200);return()=>{clearTimeout(timer);ctrl.abort();};},[api,q,status,page,revision]);
 function saved(message:string){setEdit(undefined);setImporting(false);setRevision(v=>v+1);changed(message);}
 return <><section className="panel"><div className="panel-toolbar"><div className="search"><Search size={19}/><input aria-label="Buscar cliente por nome ou CNPJ" placeholder="Buscar por nome ou CNPJ" value={q} onChange={e=>{setQ(e.target.value);setPage(0);}}/></div><select aria-label="Filtrar situação dos clientes" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">Todas as situações</option><option value="true">Ativos</option><option value="false">Inativos</option></select><div className="toolbar-actions">{admin&&<button className="secondary" onClick={()=>setImporting(true)}><Upload size={17}/>Importar planilha</button>}<button className="primary" onClick={()=>setEdit(null)}><Plus size={18}/>Novo cliente</button></div></div>
  <ErrorBox message={error}/>{loading?<Loading/>:!items.length?<Empty title={q||status?'Nenhum cliente encontrado':'Sua base de clientes começa aqui'} text={q||status?'Experimente outro nome, CNPJ ou situação.':'Cadastre o primeiro cliente ou importe a planilha da sua transportadora.'} action={q||status?undefined:'Cadastrar cliente'} onAction={()=>setEdit(null)}/>:<div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Localização</th><th>Contrato</th><th>Situação</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{items.map(c=><tr key={c.id}><td><button className="record-link" onClick={()=>setEdit(c)}>{c.nome}</button><small>{cnpj(c.cnpj)}</small></td><td>{c.cidade} / {c.estado}<small>{c.endereco}{c.numero?', '+c.numero:''}</small></td><td>{c.contrato_status==='com_contrato'?<><span className="contract">Com contrato</span><small>{c.numero_contrato}</small></>:<span className="muted">{c.contrato_status==='sem_contrato'?'Sem contrato':'Não informado'}</span>}</td><td><Badge active={c.ativo}/></td><td><div className="record-actions"><button className="text-button" onClick={()=>onHistory(c)} aria-label={'Histórico de '+c.nome}><History size={16}/>Histórico</button><button className="icon-button" aria-label={'Editar '+c.nome} onClick={()=>setEdit(c)}><ArrowUpRight size={20}/></button></div></td></tr>)}</tbody></table></div>}
  <div className="table-footer"><span>{total} {total===1?'cliente':'clientes'}{total>0&&` · ${page*20+1}–${Math.min(page*20+20,total)}`}</span><div><button className="icon-button" disabled={page===0||loading} aria-label="Página anterior" onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><span>Página {page+1}</span><button className="icon-button" disabled={(page+1)*20>=total||loading} aria-label="Próxima página" onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div></div>
 </section><div className="section-note"><FileSpreadsheet size={18}/><p>Já tem uma base? Importe arquivos Excel (.xlsx) ou LibreOffice (.ods) e confira os dados antes de salvar.</p></div>
 {edit!==undefined&&<ClientForm api={api} client={edit} onClose={()=>setEdit(undefined)} onSave={()=>saved(edit?'Cliente atualizado.':'Cliente cadastrado.')}/>}
 {importing&&<ImportForm api={api} onClose={()=>setImporting(false)} onSave={n=>saved(`${n} ${n===1?'cliente importado':'clientes importados'}.`)}/>}
 </>;
}
function ClientForm({api,client,onClose,onSave}:{api:Api;client:Client|null;onClose:()=>void;onSave:()=>void}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [contract,setContract]=useState(client?.contrato_status||'nao_informado');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const values=new FormData(e.currentTarget);const body:Record<string,unknown>={};for(const key of fields)body[key]=String(values.get(key)||'').trim()||null;body.ativo=values.get('ativo')==='true';try{await api(client?'/clientes/'+client.id:'/clientes',{method:client?'PUT':'POST',body:JSON.stringify(body)});onSave();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const close=()=>{if(!busy)onClose();};
 return <Modal title={client?'Editar cliente':'Novo cliente'} subtitle="Dados do cliente e endereço de coleta." onClose={close} wide><form onSubmit={submit}><div className="modal-body"><ErrorBox message={error}/><div className="form-grid">
 <Field label="Nome / razão social *" wide><input name="nome" defaultValue={client?.nome} required maxLength={250}/></Field><Field label="CNPJ *"><input name="cnpj" defaultValue={client?cnpj(client.cnpj):''} required placeholder="00.000.000/0000-00"/></Field><Field label="Situação"><select name="ativo" defaultValue={String(client?.ativo??true)}><option value="true">Ativo</option><option value="false">Inativo</option></select></Field>
 <div className="form-section full">Endereço de coleta</div><Field label="Rua / avenida *" wide><input name="endereco" defaultValue={client?.endereco} required maxLength={300}/></Field><Field label="Número"><input name="numero" defaultValue={client?.numero||''} maxLength={30}/></Field><Field label="Complemento"><input name="complemento" defaultValue={client?.complemento||''} maxLength={250} placeholder="Quadra, lote, sala…"/></Field><Field label="Bairro"><input name="bairro" defaultValue={client?.bairro||''} maxLength={150}/></Field><Field label="CEP"><input name="cep" defaultValue={client?.cep||''} placeholder="00000-000"/></Field><Field label="Cidade *"><input name="cidade" defaultValue={client?.cidade} required maxLength={150}/></Field><Field label="Estado *"><select name="estado" defaultValue={client?.estado||''} required><option value="">Selecione</option>{'AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ').map(uf=><option key={uf}>{uf}</option>)}</select></Field>
 <div className="form-section full">Contato e contrato</div><Field label="Telefone"><input name="telefone" type="tel" defaultValue={client?.telefone||''} maxLength={50}/></Field><Field label="E-mail"><input name="email" type="email" defaultValue={client?.email||''}/></Field><Field label="Contrato"><select name="contrato_status" value={contract} onChange={e=>setContract(e.target.value as Client['contrato_status'])}><option value="nao_informado">Não informado</option><option value="sem_contrato">Sem contrato</option><option value="com_contrato">Com contrato</option></select></Field>{contract==='com_contrato'&&<Field label="Número do contrato *"><input name="numero_contrato" defaultValue={client?.numero_contrato||''} required maxLength={100}/></Field>}
 </div></div><SaveBar busy={busy} onClose={close}/></form></Modal>;
}
type Batch={id:string;total:number;validas:number;expira_em:string;linhas:{linha:number;dados:Client|null;erros:string[]}[]};
function ImportForm({api,onClose,onSave}:{api:Api;onClose:()=>void;onSave:(n:number)=>void}){
 const [file,setFile]=useState<File|null>(null);const [batch,setBatch]=useState<Batch|null>(null);const [selected,setSelected]=useState<Set<number>>(new Set());const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function upload(e:FormEvent){e.preventDefault();if(!file)return;setBusy(true);setError('');const data=new FormData();data.append('arquivo',file);try{const result=await api<Batch>('/clientes/importacoes/previa',{method:'POST',body:data});setBatch(result);setSelected(new Set(result.linhas.filter(r=>!r.erros.length).map(r=>r.linha)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function confirm(){if(!batch||!selected.size)return;setBusy(true);setError('');try{const result=await api<{importados:number}>(`/clientes/importacoes/${batch.id}/confirmar`,{method:'POST',body:JSON.stringify({linhas:[...selected]})});onSave(result.importados);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title="Importar clientes" subtitle={batch?'2 de 2 · Confira as linhas antes de confirmar.':'1 de 2 · Selecione a planilha da sua transportadora.'} wide onClose={()=>{if(!busy)onClose();}}><div className="modal-body"><ErrorBox message={error}/>{!batch?<form onSubmit={upload}><div className="upload-area"><FileSpreadsheet size={38}/><h3>Selecione sua planilha</h3><p>Excel (.xlsx) ou LibreOffice (.ods), até 5 MB.</p><input aria-label="Planilha de clientes" type="file" accept=".xlsx,.ods" required onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);setError(f&&f.size>5*1024*1024?'O arquivo deve ter até 5 MB.':'');}}/></div><p className="helper">Use uma aba com nome, CNPJ (ou CGC), endereço, cidade e estado. E-mail e contrato são opcionais.</p><button className="primary" disabled={busy||!file||file.size>5*1024*1024}>{busy?'Conferindo…':'Conferir planilha'}<ArrowUpRight size={18}/></button></form>:<><div className="import-summary"><span><CheckCircle2 size={19}/>{batch.validas} linhas válidas</span><span>{batch.total-batch.validas} para corrigir</span><button className="text-button" disabled={busy} onClick={()=>{setBatch(null);setError('');}}>Trocar arquivo</button></div><p className="helper">Linhas com erro não serão importadas. A prévia é válida até {new Date(batch.expira_em).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}.</p><div className="table-wrap preview-table"><table><thead><tr><th><input aria-label="Selecionar todas as linhas válidas" type="checkbox" disabled={!batch.validas||busy} checked={selected.size===batch.validas&&!!batch.validas} onChange={e=>setSelected(new Set(e.target.checked?batch.linhas.filter(r=>!r.erros.length).map(r=>r.linha):[]))}/></th><th>Linha</th><th>Cliente</th><th>Conferência</th></tr></thead><tbody>{batch.linhas.map(r=><tr key={r.linha}><td><input aria-label={`Selecionar linha ${r.linha}`} type="checkbox" disabled={!!r.erros.length||busy} checked={selected.has(r.linha)} onChange={e=>setSelected(prev=>{const next=new Set(prev);e.target.checked?next.add(r.linha):next.delete(r.linha);return next;})}/></td><td>{r.linha}</td><td>{r.dados?.nome||'Confira os dados da linha'}{r.dados&&<small>{cnpj(r.dados.cnpj)}</small>}</td><td>{r.erros.length?r.erros.map((err,i)=><p className="row-error" key={i}>{err}</p>):<span className="badge green">Pronto para importar</span>}</td></tr>)}</tbody></table></div></>}</div>{batch&&<footer className="modal-footer"><span>{selected.size} selecionados</span><button className="primary" disabled={busy||!selected.size} onClick={confirm}>{busy?'Importando…':`Importar ${selected.size} clientes`}</button></footer>}</Modal>;
}
