import CollectionProof from './CollectionProof';
import OfflineConflicts from './OfflineConflicts';
import {useEffect,useState,type FormEvent} from 'react';
import {Plus,Search,ArrowUpRight,ChevronLeft,ChevronRight,ClipboardList,CheckCircle2,Clock,RefreshCw,X} from 'lucide-react';
import {type Api,type Client,type Driver,cnpj} from './api';
import {Empty,ErrorBox,Field,Loading,Modal,SaveBar} from './ui';
import './collections.css';

type Modality={id:string;nome:string;ativa:boolean};
type Item={id:string;modalidade_id:string;modalidade_nome:string;quantidade:number|null;quantidade_status:'a_conferir'|'confirmada'};
type Volume={modalidade_id:string;quantidade:string;quantidade_status:'a_conferir'|'confirmada'};
type RecordItem={id:string;tem_comprovante:boolean;cliente_id:string;cliente_nome:string;cliente_cnpj:string;motorista_nome:string;status:string;origem:string;agendada_para:string|null;concluida_em:string|null;criado_em:string;data_referencia:string;versao:number;observacoes:string|null;itens:Item[];dados_registro:{endereco:Record<string,string|null>}|null;
 eventos:{id:string;usuario_nome:string;status_anterior:string|null;status_novo:string;motivo:string|null;criado_em:string}[];
 conferencias:{id:string;modalidade_nome:string;quantidade_anterior:number|null;quantidade_nova:number;status_anterior:string;usuario_nome:string;motivo:string;criado_em:string}[]};
type History={items:RecordItem[];total:number;concluidas:number;agendadas:number;fuso_horario:string;por_modalidade:{modalidade_id:string;modalidade_nome:string;coletas:number;volumes_confirmados:number;itens_a_conferir:number}[]};
const statuses:Record<string,string>={agendada:'Agendada',concluida:'Concluída',cancelada:'Cancelada',nao_atendida:'Não atendida'};
const origins:Record<string,string>={rota_fixa:'Rota fixa',chamado_imprevisto:'Chamado imprevisto'};
const stamp=(value:string|null,zone:string)=>value?new Intl.DateTimeFormat('pt-BR',{timeZone:zone,dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'Não informado';
const localNow=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const volumesPayload=(volumes:Volume[])=>volumes.map(v=>({...v,quantidade:v.quantidade===''?null:Number(v.quantidade)}));
function CollectionBadge({value}:{value:string}){return <span className={'badge '+(value==='concluida'?'green':value==='agendada'?'blue':'gray')}>{statuses[value]}</span>;}

export default function Collections({api,admin,initialClient,initialCollectionId,changed}:{api:Api;admin:boolean;initialClient:Client|null;initialCollectionId?:string|null;changed:(message:string)=>void}){
 const [conflicts,setConflicts]=useState(false);
 const [selectedClient,setSelectedClient]=useState<Client|null>(initialClient);const [mods,setMods]=useState<Modality[]>([]);const [drivers,setDrivers]=useState<Driver[]>([]);
 const [filters,setFilters]=useState({data_inicio:'',data_fim:'',motorista_id:'',modalidade_id:'',status:'',origem:'',quantidade_status:''});
 const [page,setPage]=useState(0);const [data,setData]=useState<History|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const [creating,setCreating]=useState(false);const [detail,setDetail]=useState<RecordItem|null>(null);const [opening,setOpening]=useState(false);
 const [exporting,setExporting]=useState<'csv'|'pdf'|null>(null);
 useEffect(()=>{const ctrl=new AbortController();Promise.all([api<{items:Modality[]}>('/modalidades',{signal:ctrl.signal}),api<{items:Driver[]}>('/motoristas',{signal:ctrl.signal})]).then(([m,d])=>{setMods(m.items);setDrivers(d.items);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>ctrl.abort();},[api]);
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);const params=new URLSearchParams({limit:'20',offset:String(page*20)});for(const [key,val] of Object.entries(filters))if(val)params.set(key,val);if(selectedClient)params.set('cliente_id',selectedClient.id);api<History>('/coletas?'+params,{signal:ctrl.signal}).then(result=>{setData(result);setError('');}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setData(null);}}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false);});return()=>ctrl.abort();},[api,filters,selectedClient,page,revision]);
 const filter=(key:keyof typeof filters,value:string)=>{setFilters(prev=>({...prev,[key]:value}));setPage(0);};
 async function open(id:string){setOpening(true);setError('');try{setDetail(await api<RecordItem>('/coletas/'+id));}catch(e){setError((e as Error).message);}finally{setOpening(false);}}
 useEffect(()=>{if(initialCollectionId)open(initialCollectionId);},[initialCollectionId]);
 async function exportFile(format:'csv'|'pdf'){
  setExporting(format);setError('');const params=new URLSearchParams();for(const [key,val] of Object.entries(filters))if(val)params.set(key,val);if(selectedClient)params.set('cliente_id',selectedClient.id);
  try{const blob=await api.download(`/coletas/exportar.${format}?${params}`);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`coletas.${format}`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  catch(e){setError((e as Error).message);}finally{setExporting(null);}
 }
 const updated=(record:RecordItem,message:string)=>{setDetail(record);setRevision(n=>n+1);changed(message);};
 const zone=data?.fuso_horario||'America/Sao_Paulo';
 return <>{conflicts&&<OfflineConflicts api={api} onClose={()=>setConflicts(false)}/>}<section className="panel"><header className="panel-toolbar"><div><h2>{selectedClient?'Histórico do cliente':'Registros e histórico'}</h2><p className="helper">{selectedClient?selectedClient.nome:'Consulte as visitas e os volumes de cada modalidade.'}</p></div><div className="toolbar-actions"><button className="secondary" onClick={()=>setConflicts(true)}>Conferências offline</button><button className="primary" onClick={()=>setCreating(true)}><Plus size={18}/>Nova coleta</button></div></header>
 <div className="history-filters"><ClientPicker api={api} value={selectedClient} onChange={c=>{setSelectedClient(c);setPage(0);}}/><Field label="De"><input type="date" value={filters.data_inicio} onChange={e=>filter('data_inicio',e.target.value)}/></Field><Field label="Até"><input type="date" value={filters.data_fim} onChange={e=>filter('data_fim',e.target.value)}/></Field><Field label="Situação"><select value={filters.status} onChange={e=>filter('status',e.target.value)}><option value="">Todas</option>{Object.entries(statuses).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></Field>
 <Field label="Motorista"><select value={filters.motorista_id} onChange={e=>filter('motorista_id',e.target.value)}><option value="">Todos</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.nome}{!d.ativo?' (inativo)':''}</option>)}</select></Field><Field label="Modalidade"><select value={filters.modalidade_id} onChange={e=>filter('modalidade_id',e.target.value)}><option value="">Todas</option>{mods.map(m=><option key={m.id} value={m.id}>{m.nome}{!m.ativa?' (inativa)':''}</option>)}</select></Field><Field label="Origem"><select value={filters.origem} onChange={e=>filter('origem',e.target.value)}><option value="">Todas</option>{Object.entries(origins).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></Field><Field label="Volumes"><select value={filters.quantidade_status} onChange={e=>filter('quantidade_status',e.target.value)}><option value="">Todos</option><option value="a_conferir">A conferir</option><option value="confirmada">Confirmados</option></select></Field>
 </div><div className="history-export"><p className="history-time-note">Período pela realização das coletas concluídas e pelo agendamento das demais. Fuso: {zone}.</p><div><button className="secondary" disabled={!!exporting||loading} onClick={()=>exportFile('csv')}>{exporting==='csv'?'Gerando CSV…':'Baixar CSV'}</button><button className="secondary" disabled={!!exporting||loading} onClick={()=>exportFile('pdf')}>{exporting==='pdf'?'Gerando PDF…':'Baixar PDF'}</button></div></div><ErrorBox message={error}/>
 {loading?<Loading/>:data&&<><div className="history-totals"><span><ClipboardList size={18}/><strong>{data.total}</strong> coletas</span><span><CheckCircle2 size={18}/><strong>{data.concluidas}</strong> concluídas</span><span><Clock size={18}/><strong>{data.agendadas}</strong> agendadas</span></div>
 {!data.items.length?<Empty title="Nenhuma coleta neste filtro" text="Registre uma coleta ou ajuste cliente, período e situação para consultar o histórico."/>:<div className="table-wrap"><table><thead><tr><th>Data</th><th>Cliente / motorista</th><th>Modalidades e volumes</th><th>Situação</th><th><span className="sr-only">Detalhes</span></th></tr></thead><tbody>{data.items.map(record=><tr key={record.id}><td>{stamp(record.data_referencia,zone)}<small>{origins[record.origem]}</small></td><td><button className="record-link" disabled={opening} onClick={()=>open(record.id)}>{record.cliente_nome}</button><small>{record.motorista_nome}</small></td><td>{record.itens.map(item=><div className="volume-line" key={item.id}><span>{item.modalidade_nome}</span><strong>{item.quantidade??'—'}</strong>{item.quantidade_status==='a_conferir'&&<span className="badge amber">A conferir</span>}</div>)}</td><td><CollectionBadge value={record.status}/></td><td><button className="icon-button" aria-label={'Abrir coleta de '+record.cliente_nome} disabled={opening} onClick={()=>open(record.id)}><ArrowUpRight size={20}/></button></td></tr>)}</tbody></table></div>}
 <div className="table-footer"><span>{data.total} registros encontrados</span><div><button className="icon-button" disabled={!page} aria-label="Página anterior" onClick={()=>setPage(n=>n-1)}><ChevronLeft size={18}/></button><span>Página {page+1}</span><button className="icon-button" disabled={(page+1)*20>=data.total} aria-label="Próxima página" onClick={()=>setPage(n=>n+1)}><ChevronRight size={18}/></button></div></div>
 {!!data.por_modalidade.length&&<details className="history-breakdown" open><summary>Resumo por modalidade · apenas coletas concluídas</summary><p className="helper">O resumo considera todo o período filtrado. Estimativas a conferir não entram nos volumes confirmados. Uma visita com duas modalidades aparece em ambas.</p><div className="table-wrap"><table><thead><tr><th>Modalidade</th><th>Coletas</th><th>Volumes confirmados</th><th>Itens a conferir</th></tr></thead><tbody>{data.por_modalidade.map((m,i)=><tr key={m.modalidade_id+'-'+i}><td>{m.modalidade_nome}</td><td>{m.coletas}</td><td>{m.volumes_confirmados}</td><td>{m.itens_a_conferir}</td></tr>)}</tbody></table></div></details>}</>}
 </section>{creating&&<CreateCollection api={api} initialClient={selectedClient?.ativo?selectedClient:null} drivers={drivers} mods={mods} onClose={()=>setCreating(false)} onSave={record=>{setCreating(false);updated(record,'Coleta registrada.');}}/>}{detail&&<CollectionDetail api={api} record={detail} admin={admin} zone={zone} onClose={()=>setDetail(null)} onUpdate={updated}/>}</>;
}

function ClientPicker({api,value,onChange,activeOnly=false}:{api:Api;value:Client|null;onChange:(c:Client|null)=>void;activeOnly?:boolean}){
 const [query,setQuery]=useState('');const [options,setOptions]=useState<Client[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);const timer=setTimeout(()=>{api<{items:Client[]}>('/clientes?limit=50&q='+encodeURIComponent(query)+(activeOnly?'&ativo=true':''),{signal:ctrl.signal}).then(r=>{setOptions(r.items);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false);});},200);return()=>{clearTimeout(timer);ctrl.abort();};},[api,query,activeOnly]);
 const visible=value&&!options.some(c=>c.id===value.id)?[value,...options]:options;
 return <div className="customer-picker"><Field label={activeOnly?'Cliente *':'Cliente'}><select required={activeOnly} value={value?.id||''} onChange={e=>onChange(visible.find(c=>c.id===e.target.value)||null)}><option value="">{activeOnly?'Selecione o cliente':'Todos os clientes'}</option>{visible.map(c=><option key={c.id} value={c.id}>{c.nome}{!c.ativo?' (inativo)':''}</option>)}</select></Field><div className="search"><Search size={15}/><input aria-label="Buscar cliente pelo nome ou CNPJ" placeholder="Refinar lista pelo nome ou CNPJ" value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading&&<small role="status">Buscando…</small>}{error&&<ErrorBox message={error}/>}</div>;
}

function VolumeEditor({values,onChange,mods,locked=false}:{values:Volume[];onChange:(v:Volume[])=>void;mods:Modality[];locked?:boolean}){
 function update(index:number,change:Partial<Volume>){onChange(values.map((v,i)=>i===index?{...v,...change}:v));}
 return <div className="volume-editor"><div className="section-inline"><h3>Modalidades e volumes</h3>{!locked&&<button type="button" className="text-button" disabled={values.length>=Math.min(50,mods.length)} onClick={()=>onChange([...values,{modalidade_id:'',quantidade:'',quantidade_status:'a_conferir'}])}><Plus size={16}/>Adicionar modalidade</button>}</div>{values.map((v,i)=><div className="volume-fields" key={i}><Field label="Modalidade *"><select aria-label={`Modalidade ${i+1}`} required disabled={locked} value={v.modalidade_id} onChange={e=>update(i,{modalidade_id:e.target.value})}><option value="">Selecione</option>{mods.filter(m=>m.id===v.modalidade_id||!values.some(x=>x.modalidade_id===m.id)).map(m=><option value={m.id} key={m.id}>{m.nome}</option>)}</select></Field><Field label="Quantidade"><input aria-label={`Quantidade ${i+1}`} type="number" min="0" max="2147483647" step="1" required={v.quantidade_status==='confirmada'} value={v.quantidade} onChange={e=>update(i,{quantidade:e.target.value})} placeholder="Não contada"/></Field><Field label="Conferência"><select aria-label={`Conferência ${i+1}`} value={v.quantidade_status} onChange={e=>update(i,{quantidade_status:e.target.value as Volume['quantidade_status']})}><option value="a_conferir">A conferir</option><option value="confirmada">Confirmada</option></select></Field>{!locked&&<button type="button" className="icon-button" disabled={values.length===1} aria-label={`Remover modalidade ${i+1}`} onClick={()=>onChange(values.filter((_,j)=>i!==j))}><X size={17}/></button>}</div>)}<p className="helper">Se a quantidade ainda não foi contada, mantenha “A conferir”. Você pode deixar o valor vazio ou informar uma estimativa.</p></div>;
}

function CreateCollection({api,initialClient,drivers,mods,onClose,onSave}:{api:Api;initialClient:Client|null;drivers:Driver[];mods:Modality[];onClose:()=>void;onSave:(r:RecordItem)=>void}){
 const [selected,setSelected]=useState<Client|null>(initialClient);const [status,setStatus]=useState('agendada');const [when,setWhen]=useState(localNow);const [requestId]=useState(()=>crypto.randomUUID());
 const [volumes,setVolumes]=useState<Volume[]>([{modalidade_id:'',quantidade:'',quantidade_status:'a_conferir'}]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);setError('');const form=new FormData(e.currentTarget);try{const result=await api<RecordItem>('/coletas',{method:'POST',body:JSON.stringify({id_local_dispositivo:requestId,cliente_id:selected.id,motorista_id:form.get('motorista_id'),origem:form.get('origem'),status,agendada_para:status==='agendada'?new Date(when).toISOString():null,concluida_em:status==='concluida'?new Date(when).toISOString():null,observacoes:form.get('observacoes')||null,itens:volumesPayload(volumes)})});onSave(result);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const close=()=>{if(!busy)onClose();};
 return <Modal title="Registrar coleta" subtitle="Agende uma visita ou registre uma coleta já realizada." wide onClose={close}><form onSubmit={submit}><div className="modal-body"><ErrorBox message={error}/><div className="form-grid"><ClientPicker api={api} value={selected} onChange={setSelected} activeOnly/><Field label="Motorista *"><select name="motorista_id" required defaultValue=""><option value="">Selecione o motorista</option>{drivers.filter(d=>d.ativo).map(d=><option key={d.id} value={d.id}>{d.nome}</option>)}</select></Field><Field label="Situação"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="agendada">Agendar coleta</option><option value="concluida">Já realizada</option></select></Field><Field label={status==='agendada'?'Data e hora agendada *':'Data e hora da realização *'}><input type="datetime-local" required value={when} onChange={e=>setWhen(e.target.value)}/><small>Horário local deste dispositivo.</small></Field><Field label="Origem"><select name="origem"><option value="rota_fixa">Rota fixa</option><option value="chamado_imprevisto">Chamado imprevisto</option></select></Field><Field label="Observações"><textarea name="observacoes" maxLength={2000} rows={2}/></Field></div><VolumeEditor values={volumes} onChange={setVolumes} mods={mods.filter(m=>m.ativa)}/></div><SaveBar busy={busy} onClose={close} label="Registrar coleta"/></form></Modal>;
}

function CollectionDetail({api,record,admin,zone,onClose,onUpdate}:{api:Api;record:RecordItem;admin:boolean;zone:string;onClose:()=>void;onUpdate:(r:RecordItem,message:string)=>void}){
 const [action,setAction]=useState<string|null>(null);const [correction,setCorrection]=useState<Item|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [volumes,setVolumes]=useState<Volume[]>([]);
 const [available,setAvailable]=useState<Modality[]>([]);
 useEffect(()=>{const ctrl=new AbortController();if(!record.itens.length)api<{items:Modality[]}>('/modalidades',{signal:ctrl.signal}).then(r=>setAvailable(r.items.filter(m=>m.ativa))).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>ctrl.abort();},[api,record.id,record.itens.length]);
 const close=()=>{if(!busy)onClose();};
 async function refresh(){setBusy(true);try{const current=await api<RecordItem>('/coletas/'+record.id);onUpdate(current,'Detalhes atualizados.');setAction(null);setCorrection(null);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function startAction(next:string){setAction(next);setCorrection(null);setError('');setVolumes(record.itens.length?record.itens.map(i=>({modalidade_id:i.modalidade_id,quantidade:i.quantidade===null?'':String(i.quantidade),quantidade_status:i.quantidade_status})):[{modalidade_id:'',quantidade:'',quantidade_status:'a_conferir'}]);}
 async function saveStatus(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{const result=await api<RecordItem>('/coletas/'+record.id+'/status',{method:'PUT',body:JSON.stringify({versao:record.versao,status:action,motivo:form.get('motivo')||null,...(action==='concluida'?{concluida_em:new Date(String(form.get('concluida_em'))).toISOString(),itens:volumesPayload(volumes)}:{})})});setAction(null);onUpdate(result,'Situação da coleta atualizada.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function saveQuantity(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!correction)return;setBusy(true);setError('');const form=new FormData(e.currentTarget);try{const result=await api<RecordItem>(`/coletas/${record.id}/itens/${correction.id}/quantidade`,{method:'PUT',body:JSON.stringify({versao:record.versao,quantidade:Number(form.get('quantidade')),motivo:form.get('motivo')})});setCorrection(null);onUpdate(result,'Quantidade conferida e alteração registrada.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const address=record.dados_registro?.endereco;
 return <Modal title="Detalhes da coleta" subtitle={record.cliente_nome} wide onClose={close}><div className="modal-body"><div className="collection-detail-head"><CollectionBadge value={record.status}/><span>{origins[record.origem]}</span><button className="text-button push-right" disabled={busy} onClick={refresh}><RefreshCw size={16}/>Atualizar detalhes</button></div><ErrorBox message={error}/><dl className="detail-grid"><div><dt>Cliente no registro</dt><dd>{record.cliente_nome}<small>{cnpj(record.cliente_cnpj)}</small></dd></div><div><dt>Motorista</dt><dd>{record.motorista_nome}</dd></div><div><dt>Agendamento</dt><dd>{stamp(record.agendada_para,zone)}</dd></div><div><dt>Realização</dt><dd>{stamp(record.concluida_em,zone)}</dd></div>{address&&<div className="full"><dt>Endereço registrado</dt><dd>{[address.endereco,address.numero,address.complemento,address.bairro,address.cidade,address.estado].filter(Boolean).join(', ')}</dd></div>}{record.observacoes&&<div className="full"><dt>Observações</dt><dd className="preserve-lines">{record.observacoes}</dd></div>}</dl><CollectionProof api={api} id={record.id} available={record.tem_comprovante}/>
 <div className="table-wrap collection-items"><table><thead><tr><th>Modalidade</th><th>Quantidade</th><th>Conferência</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{record.itens.map(item=><tr key={item.id}><td>{item.modalidade_nome}</td><td>{item.quantidade??'Não informada'}</td><td><span className={'badge '+(item.quantidade_status==='confirmada'?'green':'amber')}>{item.quantidade_status==='confirmada'?'Confirmada':'A conferir'}</span></td><td>{admin&&record.status==='concluida'&&<button className="text-button" disabled={busy} onClick={()=>{setCorrection(item);setAction(null);setError('');}}>{item.quantidade_status==='a_conferir'?'Conferir':'Corrigir'}</button>}</td></tr>)}</tbody></table></div>
 {record.status==='agendada'&&!action&&<div className="collection-actions"><button className="primary" disabled={busy} onClick={()=>startAction('concluida')}><CheckCircle2 size={18}/>Concluir coleta</button><button className="secondary" disabled={busy} onClick={()=>startAction('nao_atendida')}>Não atendida</button><button className="secondary" disabled={busy} onClick={()=>startAction('cancelada')}>Cancelar coleta</button></div>}
 {action&&<form className="collection-action-form" onSubmit={saveStatus}><h3>{action==='concluida'?'Concluir coleta':action==='cancelada'?'Cancelar coleta':'Registrar não atendimento'}</h3>{action==='concluida'?<><Field label="Data e hora da realização *"><input type="datetime-local" name="concluida_em" required defaultValue={localNow()}/><small>Horário local deste dispositivo.</small></Field><VolumeEditor values={volumes} onChange={setVolumes} mods={record.itens.length?record.itens.map(i=>({id:i.modalidade_id,nome:i.modalidade_nome,ativa:true})):available} locked={!!record.itens.length}/></>:null}<Field label={action==='concluida'?'Observação da conclusão':'Motivo *'}><textarea name="motivo" required={action!=='concluida'} maxLength={1000} rows={2}/></Field><div className="collection-actions"><button className="primary" disabled={busy}>{busy?'Salvando…':'Confirmar'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setAction(null)}>Voltar</button></div></form>}
 {correction&&<form className="collection-action-form" key={correction.id} onSubmit={saveQuantity}><h3>Conferir {correction.modalidade_nome}</h3><div className="form-grid"><Field label="Quantidade real *"><input name="quantidade" type="number" min="0" max="2147483647" step="1" required defaultValue={correction.quantidade??''}/></Field><Field label="Motivo da conferência / correção *"><input name="motivo" required maxLength={1000} placeholder="Ex.: Contagem dos volumes na base"/></Field></div><p className="helper">A alteração registra o valor anterior, o responsável e a data. A quantidade ficará confirmada.</p><div className="collection-actions"><button className="primary" disabled={busy}>{busy?'Salvando…':'Confirmar quantidade'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setCorrection(null)}>Voltar</button></div></form>}
 <section className="audit-section"><h3>Histórico do registro</h3><ul>{record.eventos.map(event=><li key={event.id}><strong>{event.status_anterior?`${statuses[event.status_anterior]} → ${statuses[event.status_novo]}`:`Registro ${statuses[event.status_novo].toLowerCase()}`}</strong><span>{event.usuario_nome} · {stamp(event.criado_em,zone)}</span>{event.motivo&&<p>{event.motivo}</p>}</li>)}</ul></section>
 {!!record.conferencias.length&&<section className="audit-section"><h3>Conferências de quantidade</h3><ul>{record.conferencias.map(a=><li key={a.id}><strong>{a.modalidade_nome}: {a.quantidade_anterior??'não informada'} → {a.quantidade_nova}</strong><span>{a.usuario_nome} · {stamp(a.criado_em,zone)}</span><p>{a.motivo}</p></li>)}</ul></section>}
 <p className="helper">O comprovante, quando disponível, aparece acima. Dados de cliente e endereço são os registrados na criação da coleta.</p></div></Modal>;
}
