import {useEffect,useState,type FormEvent} from 'react';
import {Plus} from 'lucide-react';
import type {Api} from './api';
import {Badge,ErrorBox,Field,Loading,Modal,SaveBar} from './ui';

type Company={id:string;nome:string;fuso_horario:string};
type Modality={id:string;nome:string;ativa:boolean};
const suggestedZones=['America/Sao_Paulo','America/Manaus','America/Cuiaba','America/Rio_Branco','America/Noronha'];

export default function CompanySettings({api,changed}:{api:Api;changed:(s:string)=>void}){
 const [company,setCompany]=useState<Company|null>(null),[modalities,setModalities]=useState<Modality[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[edit,setEdit]=useState<Modality|null|undefined>();
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);Promise.all([api<Company>('/empresa',{signal:ctrl.signal}),api<{items:Modality[]}>('/modalidades',{signal:ctrl.signal})]).then(([c,m])=>{setCompany(c);setModalities(m.items);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false);});return()=>ctrl.abort();},[api,revision]);
 async function saveCompany(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{await api('/empresa',{method:'PUT',body:JSON.stringify({nome:data.get('nome'),fuso_horario:data.get('fuso_horario')})});setRevision(n=>n+1);changed('Dados da empresa atualizados.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><ErrorBox message={error}/>{loading?<Loading/>:company&&<><section className="panel"><div className="panel-toolbar"><div><h2>Dados da empresa</h2><p className="helper">Código de acesso: <code>{company.id}</code></p></div></div><form className="settings-form" onSubmit={saveCompany}><Field label="Nome da transportadora"><input name="nome" defaultValue={company.nome} required maxLength={250}/></Field><Field label="Fuso horário"><input name="fuso_horario" defaultValue={company.fuso_horario} list="fusos-brasil" required maxLength={100}/><datalist id="fusos-brasil">{suggestedZones.map(z=><option key={z} value={z}/>)}</datalist></Field><p className="helper">O fuso define a data dos relatórios e dos novos atendimentos. Execuções já emitidas preservam seu fuso, mas datas exibidas no histórico passam a usar o novo fuso.</p><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar dados da empresa'}</button></form></section><section className="panel settings-panel"><div className="panel-toolbar"><div><h2>Modalidades de coleta</h2><p className="helper">Cadastre os serviços que a equipe seleciona ao registrar volumes.</p></div><button className="primary push-right" onClick={()=>setEdit(null)}><Plus size={18}/>Nova modalidade</button></div><div className="table-wrap"><table><thead><tr><th>Nome</th><th>Situação</th><th>Ação</th></tr></thead><tbody>{modalities.map(m=><tr key={m.id}><td>{m.nome}</td><td><Badge active={m.ativa}/></td><td><button className="text-button" onClick={()=>setEdit(m)}>Editar</button></td></tr>)}</tbody></table></div></section><p className="section-note">Desativar impede novos registros nessa modalidade. O nome usado em coletas anteriores continua no histórico.</p></>}{edit!==undefined&&<ModalityForm api={api} value={edit} onClose={()=>setEdit(undefined)} onSave={()=>{setEdit(undefined);setRevision(n=>n+1);changed(edit?'Modalidade atualizada.':'Modalidade criada.');}}/>}</>;
}

function ModalityForm({api,value,onClose,onSave}:{api:Api;value:Modality|null;onClose:()=>void;onSave:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{await api(value?`/modalidades/${value.id}`:'/modalidades',{method:value?'PUT':'POST',body:JSON.stringify({nome:data.get('nome'),ativa:data.get('ativa')==='true'})});onSave();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={value?'Editar modalidade':'Nova modalidade'} onClose={()=>{if(!busy)onClose();}}><form onSubmit={submit}><div className="modal-body"><ErrorBox message={error}/><Field label="Nome"><input name="nome" defaultValue={value?.nome} required maxLength={150}/></Field><Field label="Situação"><select name="ativa" defaultValue={String(value?.ativa??true)}><option value="true">Ativa</option><option value="false">Inativa</option></select></Field></div><SaveBar busy={busy} onClose={onClose} label={value?'Salvar modalidade':'Criar modalidade'}/></form></Modal>;
}
