import {useEffect,useState,type FormEvent} from 'react';
import {Plus,Car, Bike,ArrowUpRight,Truck} from 'lucide-react';
import {type Api,type Driver,vehicleNames} from './api';
import {Badge,Empty,ErrorBox,Field,Loading,Modal,SaveBar} from './ui';
export default function Drivers({api,admin,changed}:{api:Api;admin:boolean;changed:(s:string)=>void}){
 const [items,setItems]=useState<Driver[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [edit,setEdit]=useState<Driver|null|undefined>();const [revision,setRevision]=useState(0);
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);api<{items:Driver[]}>('/motoristas',{signal:ctrl.signal}).then(r=>{setItems(r.items);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false);});return()=>ctrl.abort();},[api,revision]);
 return <><section className="panel"><div className="panel-toolbar"><div><h2>Equipe e veículos</h2><p className="helper">{items.filter(m=>m.ativo).length} motoristas ativos na operação</p></div>{admin&&<button className="primary push-right" onClick={()=>setEdit(null)}><Plus size={18}/>Novo motorista</button>}</div><ErrorBox message={error}/>{loading?<Loading/>:!items.length?<Empty title="Cadastre sua equipe" text="Vincule cada motorista ao veículo que ele utiliza nas coletas." action={admin?'Cadastrar motorista':undefined} onAction={()=>setEdit(null)}/>:<div className="driver-grid">{items.map(m=>{const Icon=m.tipo==='moto'?Bike:m.tipo==='carro'?Car:Truck;return <article className="driver-card" key={m.id}><div className="driver-card-top"><span className="vehicle-icon"><Icon size={27}/></span><Badge active={m.ativo}/></div><h3>{m.nome}</h3><span className="muted">Usuário: {m.login}</span><div className="vehicle-line"><strong>{vehicleNames[m.tipo]||'Sem veículo'}</strong><span className="plate">{m.placa||'—'}</span></div><footer><span>{m.rotas_ativas} {m.rotas_ativas===1?'rota ativa':'rotas ativas'}</span>{admin&&<button className="text-button" onClick={()=>setEdit(m)}>Editar<ArrowUpRight size={17}/></button>}</footer></article>;})}</div>}</section><p className="section-note">O acesso do motorista é individual. Localização e aplicativo Android estarão disponíveis nas próximas etapas.</p>{edit!==undefined&&<DriverForm api={api} driver={edit} onClose={()=>setEdit(undefined)} onSave={()=>{setEdit(undefined);setRevision(n=>n+1);changed(edit?'Motorista atualizado.':'Motorista cadastrado.');}}/>}</>;
}
function DriverForm({api,driver,onClose,onSave}:{api:Api;driver:Driver|null;onClose:()=>void;onSave:()=>void}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const body={nome:form.get('nome'),login:form.get('login'),senha:form.get('senha')||null,tipo:form.get('tipo'),placa:form.get('placa'),ativo:form.get('ativo')==='true'};try{await api(driver?'/motoristas/'+driver.id:'/motoristas',{method:driver?'PUT':'POST',body:JSON.stringify(body)});onSave();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const close=()=>{if(!busy)onClose();};
 return <Modal title={driver?'Editar motorista':'Novo motorista'} subtitle="Cadastre o acesso individual e o veículo de trabalho." onClose={close}><form onSubmit={submit}><div className="modal-body"><ErrorBox message={error}/><div className="form-grid"><Field label="Nome completo *" wide><input name="nome" defaultValue={driver?.nome} required maxLength={250}/></Field><Field label="Usuário de acesso *"><input name="login" defaultValue={driver?.login} required maxLength={150} autoComplete="off"/></Field><Field label={driver?'Nova senha (opcional)':'Senha de acesso *'}><input name="senha" type="password" minLength={12} maxLength={256} required={!driver} autoComplete="new-password" placeholder="Mínimo de 12 caracteres"/></Field><div className="form-section full">Veículo</div><Field label="Tipo *"><select name="tipo" defaultValue={driver?.tipo||'carro'}>{Object.entries(vehicleNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="Placa *"><input name="placa" defaultValue={driver?.placa} required placeholder="ABC1D23" maxLength={8} style={{textTransform:'uppercase'}}/></Field><Field label="Situação" wide><select name="ativo" defaultValue={String(driver?.ativo??true)}><option value="true">Ativo</option><option value="false">Inativo</option></select></Field></div>{driver&&<p className="helper">Antes de desativar um motorista, desative ou transfira suas rotas ativas. Uma nova senha encerra as sessões existentes.</p>}</div><SaveBar busy={busy} onClose={close}/></form></Modal>;
}
