import {useEffect,useState,type FormEvent} from 'react';
import type {Api} from './api';
import {ErrorBox,Field,Loading,Modal,SaveBar} from './ui';

export default function RecoveryCodes({api,onClose}:{api:Api;onClose:()=>void}){
 const [total,setTotal]=useState<number|null>(null),[codes,setCodes]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const ctrl=new AbortController();api<{total:number}>('/auth/recuperacao/codigos',{signal:ctrl.signal}).then(r=>setTotal(r.total)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>ctrl.abort();},[api]);
 async function generate(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await api<{codigos:string[]}>('/auth/recuperacao/codigos',{method:'POST',body:JSON.stringify({senha_atual:data.get('senha_atual')})});setCodes(r.codigos);setTotal(r.codigos.length);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title="Códigos de recuperação" subtitle="Permitem redefinir sua senha caso você a esqueça." onClose={()=>{if(!busy)onClose();}}><div className="modal-body"><ErrorBox message={error}/>{total===null?<Loading/>:<p className="helper">{total} códigos disponíveis. Gerar novos códigos invalida os anteriores. Cada código funciona uma vez.</p>}{codes.length?<><div className="recovery-codes" aria-label="Novos códigos de recuperação">{codes.map(code=><code key={code}>{code}</code>)}</div><p className="helper">Guarde estes códigos em local seguro. Eles aparecem somente agora e não serão exibidos novamente.</p><button className="primary" onClick={()=>{const blob=new Blob([codes.join('\n')+'\n'],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='coleta-codigos-recuperacao.txt';a.click();URL.revokeObjectURL(url);}}>Baixar códigos</button></>:<form onSubmit={generate}><Field label="Confirme sua senha atual"><input name="senha_atual" type="password" required autoComplete="current-password"/></Field><div className="recovery-actions"><button className="primary" disabled={busy}>{busy?'Gerando…':'Gerar 8 códigos'}</button></div></form>}</div></Modal>;
}
