import DailyOperations from './DailyOperations';
import {useEffect,useState,type FormEvent} from 'react';
import {Plus,ArrowUpRight,Route as RouteIcon,Truck,MapPin,Search,GripVertical,ArrowUp,ArrowDown,X} from 'lucide-react';
import {type Api,type Route,type Stop,type Client,type Driver,days,vehicleNames} from './api';
import {Badge,Empty,ErrorBox,Field,Loading,Modal,SaveBar} from './ui';
export default function Routes({api,changed}:{api:Api;changed:(s:string)=>void}){
 const [daily,setDaily]=useState<Route|null>(null);
 const [items,setItems]=useState<Route[]>([]);const [loading,setLoading]=useState(true);const [opening,setOpening]=useState(false);const [error,setError]=useState('');const [edit,setEdit]=useState<Route|null|undefined>();const [revision,setRevision]=useState(0);
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);api<{items:Route[]}>('/rotas',{signal:ctrl.signal}).then(r=>{setItems(r.items);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false);});return()=>ctrl.abort();},[api,revision]);
 async function open(id:string){setOpening(true);setError('');try{setEdit(await api<Route>('/rotas/'+id));}catch(e){setError((e as Error).message);}finally{setOpening(false);}}
 return <><section className="panel"><div className="panel-toolbar"><div><h2>Planejamento recorrente</h2><p className="helper">Defina os dias e a sequência de atendimento de cada rota.</p></div><button className="primary push-right" onClick={()=>setEdit(null)} disabled={opening}><Plus size={18}/>Nova rota</button></div><ErrorBox message={error}/>{loading?<Loading/>:!items.length?<Empty title="Organize a primeira rota" text="Escolha um motorista, os dias de atendimento e os clientes na ordem da coleta." action="Montar rota" onAction={()=>setEdit(null)}/>:<div className="route-grid">{items.map(r=><article className="route-card" key={r.id}><div className="route-card-top"><span className="route-icon"><RouteIcon size={23}/></span><Badge active={r.ativa}/></div><h3>{r.nome}</h3><p><Truck size={17}/>{r.motorista_nome}</p><small>{vehicleNames[r.tipo]||''} {r.placa?'· '+r.placa:''}</small><div className="day-strip" aria-label="Dias da rota">{days.map((d,i)=><span key={d} className={r.dias_semana.includes(i+1)?'on':''}>{d}</span>)}</div><button className="secondary" disabled={opening} onClick={()=>setDaily(r)}>Acompanhar operação do dia</button><footer><span><MapPin size={16}/>{r.total_paradas} paradas</span><button className="text-button" disabled={opening} onClick={()=>open(r.id)}>Abrir rota<ArrowUpRight size={17}/></button></footer></article>)}</div>}</section><div className="section-note"><RouteIcon size={18}/><p>As rotas seguem a ordem definida pela equipe. Mapa e rastreamento serão integrados em uma próxima etapa.</p></div>{daily&&<DailyOperations api={api} route={daily} onClose={()=>setDaily(null)}/>}{edit!==undefined&&<RouteForm api={api} route={edit} onClose={()=>setEdit(undefined)} onSave={()=>{setEdit(undefined);setRevision(n=>n+1);changed(edit?'Rota atualizada.':'Rota cadastrada.');}}/>}</>;
}
function RouteForm({api,route,onClose,onSave}:{api:Api;route:Route|null;onClose:()=>void;onSave:()=>void}){
 const [drivers,setDrivers]=useState<Driver[]>([]);const [clients,setClients]=useState<Client[]>([]);const [query,setQuery]=useState('');const [stops,setStops]=useState<Stop[]>(route?.paradas||[]);const [week,setWeek]=useState<number[]>(route?.dias_semana||[1,2,3,4,5]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [lookupError,setLookupError]=useState('');const [searching,setSearching]=useState(true);const [drag,setDrag]=useState<number|null>(null);
 useEffect(()=>{const ctrl=new AbortController();api<{items:Driver[]}>('/motoristas',{signal:ctrl.signal}).then(r=>setDrivers(r.items)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>ctrl.abort();},[api]);
 useEffect(()=>{const ctrl=new AbortController();setSearching(true);const timer=setTimeout(()=>{api<{items:Client[]}>('/clientes?ativo=true&limit=50&q='+encodeURIComponent(query),{signal:ctrl.signal}).then(r=>{setClients(r.items);setLookupError('');}).catch(e=>{if(e.name!=='AbortError')setLookupError(e.message);}).finally(()=>{if(!ctrl.signal.aborted)setSearching(false);});},200);return()=>{clearTimeout(timer);ctrl.abort();};},[api,query]);
 function move(from:number,to:number){if(to<0||to>=stops.length)return;setStops(prev=>{const next=[...prev];next.splice(to,0,next.splice(from,1)[0]);return next;});}
 function add(c:Client){if(stops.some(s=>s.cliente_id===c.id))return;setStops(prev=>[...prev,{cliente_id:c.id,nome:c.nome,endereco:c.endereco,numero:c.numero,cidade:c.cidade,estado:c.estado,janela_inicio:null,janela_fim:null}]);}
 function window(index:number,key:'janela_inicio'|'janela_fim',value:string){setStops(prev=>prev.map((s,i)=>i===index?{...s,[key]:value||null}:s));}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!stops.length||!week.length){setError('Escolha pelo menos um dia e uma parada.');return;}setBusy(true);setError('');const values=new FormData(e.currentTarget);const body={nome:values.get('nome'),motorista_id:values.get('motorista_id'),ativa:values.get('ativa')==='true',dias_semana:week,versao:route?.versao??null,paradas:stops.map(({cliente_id,janela_inicio,janela_fim})=>({cliente_id,janela_inicio,janela_fim}))};try{await api(route?'/rotas/'+route.id:'/rotas',{method:route?'PUT':'POST',body:JSON.stringify(body)});onSave();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const close=()=>{if(!busy)onClose();};const available=clients.filter(c=>!stops.some(s=>s.cliente_id===c.id));
 return <Modal title={route?'Editar rota':'Montar nova rota'} subtitle="Defina a rotina e organize as paradas na ordem de atendimento." wide onClose={close}><form onSubmit={submit}><div className="modal-body"><ErrorBox message={error}/><div className="form-grid"><Field label="Nome da rota *" wide><input name="nome" defaultValue={route?.nome} placeholder="Ex.: Região Norte — manhã" required maxLength={200}/></Field><Field label="Motorista *"><select name="motorista_id" defaultValue={route?.motorista_id||''} required><option value="">Selecione um motorista</option>{drivers.filter(d=>d.ativo||d.id===route?.motorista_id).map(d=><option key={d.id} value={d.id}>{d.nome} · {d.placa}{!d.ativo?' (inativo)':''}</option>)}</select></Field><Field label="Situação"><select name="ativa" defaultValue={String(route?.ativa??true)}><option value="true">Ativa</option><option value="false">Inativa</option></select></Field><fieldset className="week-picker full"><legend>Dias de atendimento *</legend>{days.map((day,i)=><label key={day}><input type="checkbox" checked={week.includes(i+1)} onChange={e=>setWeek(prev=>e.target.checked?[...prev,i+1]:prev.filter(d=>d!==i+1))}/><span>{day}</span></label>)}</fieldset></div>
 <div className="route-builder"><section className="client-picker"><h3>Adicionar clientes</h3><div className="search"><Search size={17}/><input placeholder="Buscar cliente" aria-label="Buscar cliente para adicionar à rota" value={query} onChange={e=>setQuery(e.target.value)}/></div><ErrorBox message={lookupError}/>{searching?<Loading/>:<div className="picker-list">{available.length?available.map(c=><button type="button" key={c.id} onClick={()=>add(c)} disabled={stops.length>=200}><span><strong>{c.nome}</strong><small>{c.cidade} / {c.estado}</small></span><Plus size={18}/></button>):<p className="helper">Nenhum cliente disponível nesta busca.</p>}</div>}<p className="helper">Até 50 resultados por busca. Digite parte do nome ou CNPJ para refinar.</p></section>
 <section className="stop-editor"><div className="stop-title"><h3>Sequência de coleta</h3><span>{stops.length} paradas</span></div><p className="helper">Arraste ou use as setas para reordenar.</p>{!stops.length?<div className="stop-empty"><MapPin size={27}/><p>Adicione os clientes para montar o caminho.</p></div>:<ol className="stops">{stops.map((s,i)=><li key={s.cliente_id} className={drag===i?'dragging':''} onDragOver={e=>{if(drag!==null)e.preventDefault();}} onDrop={e=>{e.preventDefault();if(drag!==null)move(drag,i);setDrag(null);}}><div className="stop-main"><button type="button" className="drag-handle" draggable aria-label={'Arrastar '+s.nome} onDragStart={e=>{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',s.cliente_id);setDrag(i);}} onDragEnd={()=>setDrag(null)}><GripVertical size={19}/></button><span className="stop-number">{i+1}</span><div className="stop-name"><strong>{s.nome}</strong><small>{s.endereco}{s.numero?', '+s.numero:''}{s.cliente_ativo===false?' · Cliente inativo':''}</small></div><button type="button" className="icon-button" aria-label={'Remover '+s.nome} onClick={()=>setStops(prev=>prev.filter(x=>x.cliente_id!==s.cliente_id))}><X size={16}/></button></div><div className="stop-bottom"><div className="time-window"><label><span>Das</span><input aria-label={'Início da janela de '+s.nome} type="time" value={s.janela_inicio?.slice(0,5)||''} onChange={e=>window(i,'janela_inicio',e.target.value)}/></label><label><span>às</span><input aria-label={'Fim da janela de '+s.nome} type="time" value={s.janela_fim?.slice(0,5)||''} onChange={e=>window(i,'janela_fim',e.target.value)}/></label></div><div className="stop-arrows"><button type="button" className="icon-button" disabled={!i} onClick={()=>move(i,i-1)} aria-label={'Mover '+s.nome+' para cima'}><ArrowUp size={16}/></button><button type="button" className="icon-button" disabled={i===stops.length-1} onClick={()=>move(i,i+1)} aria-label={'Mover '+s.nome+' para baixo'}><ArrowDown size={16}/></button></div></div></li>)}</ol>}</section></div>
 </div><SaveBar busy={busy} onClose={close} label={route?'Salvar rota':'Criar rota'}/></form></Modal>;
}
