import {useEffect,useState,type FormEvent} from 'react';
import {Plus} from 'lucide-react';
import type {Api} from './api';
import {Badge,Empty,ErrorBox,Field,Loading,Modal,SaveBar} from './ui';

type StaffUser={id:string;nome:string;login:string;perfil:'admin'|'operador'|'agendamento';ativo:boolean};
const roles:Record<StaffUser['perfil'],string>={admin:'Administrador',operador:'Operador',agendamento:'Agendamento'};

export default function Users({api,currentId,changed}:{api:Api;currentId:string;changed:(s:string)=>void}){
 const [items,setItems]=useState<StaffUser[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const [modal,setModal]=useState<'new'|'reset'|null>(null),[selected,setSelected]=useState<StaffUser|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);api<{items:StaffUser[]}>('/usuarios',{signal:ctrl.signal}).then(r=>{setItems(r.items);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false);});return()=>ctrl.abort();},[api,revision]);
 async function toggle(user:StaffUser){if(!user.ativo&&!window.confirm(`Reativar o acesso de ${user.nome}?`))return;if(user.ativo&&!window.confirm(`Bloquear ${user.nome} e encerrar as sessões abertas?`))return;setError('');try{await api(`/usuarios/${user.id}/acesso`,{method:'PUT',body:JSON.stringify({ativo:!user.ativo})});setRevision(n=>n+1);changed(user.ativo?'Acesso bloqueado e sessões encerradas.':'Acesso reativado.');}catch(e){setError((e as Error).message);}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);if(data.get('senha')!==data.get('confirmacao')){setFormError('As senhas precisam ser iguais.');return;}setBusy(true);setFormError('');try{if(modal==='new')await api('/usuarios',{method:'POST',body:JSON.stringify({nome:data.get('nome'),login:data.get('login'),perfil:data.get('perfil'),senha:data.get('senha')})});else if(selected)await api(`/usuarios/${selected.id}/senha`,{method:'POST',body:JSON.stringify({nova_senha:data.get('senha')})});setModal(null);setSelected(null);setRevision(n=>n+1);changed(modal==='new'?'Acesso criado.':'Senha redefinida e sessões encerradas.');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 return <><section className="panel"><div className="panel-toolbar"><div><h2>Acessos à operação</h2><p className="helper">Gestores e equipe de agendamento. Motoristas são gerenciados na aba Motoristas.</p></div><button className="primary push-right" onClick={()=>{setFormError('');setModal('new');}}><Plus size={18}/>Novo acesso</button></div><ErrorBox message={error}/>{loading?<Loading/>:!items.length?<Empty title="Nenhum acesso cadastrado" text="Crie o primeiro acesso da equipe."/>:<div className="table-wrap"><table><thead><tr><th>Nome</th><th>Usuário</th><th>Perfil</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{items.map(user=><tr key={user.id}><td><strong>{user.nome}</strong>{user.id===currentId&&<small>Sua conta</small>}</td><td>{user.login}</td><td>{roles[user.perfil]}</td><td><Badge active={user.ativo}/></td><td><div className="user-actions">{user.id!==currentId&&<><button className="text-button" onClick={()=>{setSelected(user);setFormError('');setModal('reset');}}>Redefinir senha</button><button className="text-button" onClick={()=>toggle(user)}>{user.ativo?'Bloquear':'Reativar'}</button></>}</div></td></tr>)}</tbody></table></div>}</section><p className="section-note">Bloquear ou redefinir a senha encerra imediatamente as sessões abertas. Para trocar sua própria senha, use “Minha senha” no menu lateral.</p>
 {modal&&<Modal title={modal==='new'?'Novo acesso':'Redefinir senha'} subtitle={modal==='reset'?`Defina uma nova senha para ${selected?.nome}.`:undefined} onClose={()=>{if(!busy)setModal(null);}}><form onSubmit={submit}><div className="modal-body"><ErrorBox message={formError}/>{modal==='new'&&<><Field label="Nome"><input name="nome" required maxLength={250}/></Field><Field label="Usuário"><input name="login" required maxLength={150} autoComplete="off"/></Field><Field label="Perfil"><select name="perfil" defaultValue="agendamento"><option value="agendamento">Agendamento</option><option value="operador">Operador</option><option value="admin">Administrador</option></select></Field></>}<Field label="Nova senha (mínimo 12 caracteres)"><input name="senha" type="password" required minLength={12} maxLength={256} autoComplete="new-password"/></Field><Field label="Confirmar senha"><input name="confirmacao" type="password" required minLength={12} maxLength={256} autoComplete="new-password"/></Field></div><SaveBar busy={busy} onClose={()=>setModal(null)} label={modal==='new'?'Criar acesso':'Redefinir senha'}/></form></Modal>}</>;
}
